#define ENCODERS 5
#define BUTTONS 6
#define OSCILLATORS 4
#define WAVEFORMS 2

#define HW_VER_MAJOR 1
#define HW_VER_MINOR 0
#define HW_VER_PATCH 1

#define SW_VER_MAJOR 1
#define SW_VER_MINOR 0
#define SW_VER_PATCH 1

#define HEADER_HEIGHT 32
#define HEADER_WIDTH 160

#define DATA_X 15
#define DATA_Y 40
#define DATA_VALUE_X 185
#define DATA_SPACING 20

#define FOOTER_Y 210

#define DELAY_MIN 0.0
#define DELAY_DEF 0.0
#define DELAY_MAX 11800
#define ATTACK_MIN 0.0
#define ATTACK_DEF 10.5
#define ATTACK_MAX 11880.0
#define HOLD_MIN 0.0
#define HOLD_DEF 2.5
#define HOLD_MAX 11800.0
#define DECAY_MIN 0.0
#define DECAY_DEF 35.0
#define DECAY_MAX 11880.0
#define SUSTAIN_MIN 0.0
#define SUSTAIN_DEF 0.75
#define SUSTAIN_MAX 1.0
#define RELEASE_MIN 0.0
#define RELEASE_DEF 100
#define RELEASE_MAX 11880.0

#define WAVEFORM_SINE 0
#define WAVEFORM_SAWTOOTH 1
#define WAVEFORM_SAWTOOTH_REVERSE 2
#define WAVEFORM_SQUARE 3
#define WAVEFORM_TRIANGLE 4
#define WAVEFORM_TRIANGLE_VARIABLE 5
#define WAVEFORM_ARBITRARY 6
#define WAVEFORM_PULSE 7
#define WAVEFORM_SAMPLE_HOLD 8
